---
- hosts: dev
  become: yes
  gather_facts: false
  tasks:
    - name: Case insensitive password string match
      expect:
        command: passwd username
        responses:
          (?i)password: "MySekretPa$$word"
  # you don't want to show passwords in your logs
      no_log: true
